In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([0, 25, 0.5, 0.75, 1.0])
s

0     0.00
1    25.00
2     0.50
3     0.75
4     1.00
dtype: float64

In [3]:
s.values # 시리즈 밸류만 보겠다

array([ 0.  , 25.  ,  0.5 ,  0.75,  1.  ])

In [4]:
s.index #Rangeindex => 범위로 되어 있음

RangeIndex(start=0, stop=5, step=1)

In [5]:
s = pd.Series([0, 25, 0.5, 0.75, 1.0], index=['a','b','c','d','e'])
s

a     0.00
b    25.00
c     0.50
d     0.75
e     1.00
dtype: float64

In [6]:
s1 = s.sort_index()
s1

a     0.00
b    25.00
c     0.50
d     0.75
e     1.00
dtype: float64

In [7]:
s[['c','e']] #원하는 인덱스 출력

c    0.5
e    1.0
dtype: float64

In [8]:
'b' in s

True

In [9]:
s = pd.Series([0, 25, 0.5, 0.75, 1.0], index=[2,4,6,8,10])
s

2      0.00
4     25.00
6      0.50
8      0.75
10     1.00
dtype: float64

In [10]:
s.unique()

array([ 0.  , 25.  ,  0.5 ,  0.75,  1.  ])

In [11]:
s.value_counts() #데이터 각각 몇 개인지

0.00     1
25.00    1
0.50     1
0.75     1
1.00     1
dtype: int64

In [12]:
s.isin([0.25,0.75]) # 원하는 인덱스가 어디있는지 bool로 표현

2     False
4     False
6     False
8      True
10    False
dtype: bool

In [13]:
pop_tuple = {'서울특별시':9720846, 
             '부산광역시':3404423,
             '인천광역시':2947217,
             '대구광역시':2427954,
             '대전광역시':1471040,
             '광주광역시':1455048}

population = pd.Series(pop_tuple)  #튜플 상태
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [14]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

In [15]:
#DataFrame  pd.DataFrame[{},{}] {}값 한행씩
pd.DataFrame([{'A':2, 'B':3, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  3  3.0  NaN
1  4  5  NaN  7.0

In [16]:
pd.DataFrame(np.random.rand(5,5), 
             columns=['A','B','C','D','E'],
             index=[1,2,3,4,5])

A         B         C         D         E
1  0.851350  0.013147  0.879586  0.117121  0.998209
2  0.995800  0.308890  0.924993  0.400594  0.053754
3  0.398998  0.264759  0.154755  0.266601  0.880955
4  0.602944  0.680577  0.246253  0.422458  0.971895
5  0.366760  0.797978  0.353129  0.518030  0.966369

In [17]:
male_tuple = {'서울특별시':4732250, 
             '부산광역시':1668618,
             '인천광역시':1476813,
             '대구광역시':1198815,
             '대전광역시':734441,
             '광주광역시':720060}
male = pd.Series(male_tuple)
male

서울특별시    4732250
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [18]:
female_tuple = {'서울특별시':4988571, 
             '부산광역시':1735805,
             '인천광역시':1470404,
             '대구광역시':1229139,
             '대전광역시':736559,
             '광주광역시':734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736559
광주광역시     734988
dtype: int64

In [19]:
korea_df = pd.DataFrame({'인구수' : population,
                         '남자인구수' : male,
                         '여자인구수' : female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732250  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736559
광주광역시  1455048   720060   734988

In [20]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [21]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [22]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736559
광주광역시     734988
Name: 여자인구수, dtype: int64

In [23]:
korea_df['서울특별시':'인천광역시'] #인덱스 슬라이싱 가능
                                    #컬럼 슬라이싱 불가

인구수    남자인구수    여자인구수
서울특별시  9720846  4732250  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

In [24]:
# index 객체
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [25]:
idx[1]

4

In [26]:
idx[1:2:2]     #[a:b:2] a~b까지 2스텝으로 

Int64Index([4], dtype='int64')

In [27]:
idx[-1::]

Int64Index([10], dtype='int64')

In [28]:
print(idx)
print(idx.size)
print(idx.shape) #(5,) 1차원 shape을 가짐

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)


In [29]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')


In [30]:
idx1

Int64Index([1, 2, 4, 6, 8], dtype='int64')

In [31]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [32]:
s.keys

<bound method Series.keys of 0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64>

In [33]:
list(s.items())

[(0, 0.0), (1, 0.25), (2, 0.5), (3, 0.75), (4, 1.0)]

In [34]:
s['f'] = 1.25
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
f    1.25
dtype: float64

In [35]:
s[1:3]

1    0.25
2    0.50
dtype: float64

In [36]:
s[(s>0.4) & (s<0.8)]

2    0.50
3    0.75
dtype: float64

In [37]:
s = pd.Series([0, 25, 0.5, 0.75, 1.0])
s

0     0.00
1    25.00
2     0.50
3     0.75
4     1.00
dtype: float64

In [38]:
s.reindex(range(10))

0     0.00
1    25.00
2     0.50
3     0.75
4     1.00
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
dtype: float64

In [39]:
s.reindex(range(10), method = 'bfill')

0     0.00
1    25.00
2     0.50
3     0.75
4     1.00
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
dtype: float64

In [40]:
#DF 인뎅싱
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732250  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736559
광주광역시  1455048   720060   734988

In [41]:
korea_df['남자인구수']

서울특별시    4732250
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [42]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736559
광주광역시     734988
Name: 여자인구수, dtype: int64

In [43]:
korea_df['남여비율'] = (korea_df['남자인구수'] *100 
                    / korea_df['여자인구수'])

In [44]:
korea_df.남여비율

서울특별시     94.861835
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.712447
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [45]:
korea_df.values

array([[9.72084600e+06, 4.73225000e+06, 4.98857100e+06, 9.48618352e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36559000e+05, 9.97124467e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [46]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732250e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365590e+05   
남여비율   9.486184e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.971245e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [47]:
korea_df.loc[:'인천광역시',:'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732250
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [48]:
korea_df.loc[(korea_df.여자인구수>1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732250  4988571   94.861835
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [49]:
# 다중 인덱스
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732250  4988571   94.861835
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736559   99.712447
광주광역시  1455048   720060   734988   97.968946

In [50]:
idx_tuples = [('서울특별시',2010), ('서울특별시',2020),
              ('부산광역시',2010), ('부산광역시',2020),
              ('인천광역시',2010), ('인천광역시',2020),
              ('대구광역시',2010), ('대구광역시',2020),
              ('대전광역시',2010), ('대전광역시',2020),
              ('광주광역시',2010), ('광주광역시',2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [51]:
pop_tuples = [10312545, 9720846,
              2567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503663, 1471040,
              1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503663
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [52]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [53]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503663
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [54]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503663
광주광역시     1454636
dtype: int64

In [55]:
population['대전광역시', :]

2010    1503663
2020    1471040
dtype: int64

In [56]:
korea_mdf = population.unstack() #unstack 일반적인 DF로 변환
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503663  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [57]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503663
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [58]:
male_tuples = [5111259, 4732275, 1773170, 1668618,
              1490356, 1476813, 1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1490356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [59]:
korea_mdf = pd.DataFrame({'총인구수':population, '남자인구수':male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1490356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503663   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [60]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 129139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 129139,
 750016,
 736599,
 732856,
 734988]

In [61]:
df = pd.DataFrame(np.random.rand(6, 3),
                 index=[['a','a','b','b','c','c'], [1,2,1,2,1,2]],
                 columns=['c1','c2','c3'])
df

c1        c2        c3
a 1  0.895385  0.920374  0.005390
  2  0.220190  0.985460  0.539734
b 1  0.418820  0.262363  0.635696
  2  0.243313  0.947652  0.945924
c 1  0.706334  0.015526  0.207864
  2  0.385394  0.010317  0.624774

In [62]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'], [1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [63]:
pd.MultiIndex.from_tuples([('a',1),('a',2)])

MultiIndex([('a', 1),
            ('a', 2)],
           )

In [64]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503663
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [65]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    9
1    9
2    7
3    1
4    3
dtype: int32

In [66]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)),
                 columns=['A','B','C'])
df

A  B  C
0  6  4  6
1  5  2  9
2  9  7  9

In [67]:
np.exp(s)

0    8103.083928
1    8103.083928
2    1096.633158
3       2.718282
4      20.085537
dtype: float64

In [68]:
np.cos(df * np.pi /4)

A             B             C
0 -1.836970e-16 -1.000000e+00 -1.836970e-16
1 -7.071068e-01  6.123234e-17  7.071068e-01
2  7.071068e-01  7.071068e-01  7.071068e-01

In [69]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0,1,2,3,4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1,2,3,4,5])
s1 + s2 # 인덱스 기준

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [70]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [71]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3,3)),
                  columns=list('ACD'))
df1

A   C   D
0  7  18   2
1  4   6  15
2  6  18  16

In [72]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5,5)),
                  columns=list('BAECD'))
df2

B   A   E   C   D
0  11   1   9  11  19
1  16   8   0  19  10
2   9  19  18  14  19
3   5  15  13  14   2
4  12  18   3  17   5

In [73]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0   8.000000  21.222222  29.000000  21.000000  19.222222
1  12.000000  26.222222  25.000000  25.000000  10.222222
2  25.000000  19.222222  32.000000  35.000000  28.222222
3  25.222222  15.222222  24.222222  12.222222  23.222222
4  28.222222  22.222222  27.222222  15.222222  13.222222

In [74]:
a = np.random.randint(1, 10, size=(3,3))
a

array([[3, 5, 3],
       [9, 8, 5],
       [9, 1, 9]])

In [75]:
a + a[0]

array([[ 6, 10,  6],
       [12, 13,  8],
       [12,  6, 12]])

In [76]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  3  5  3
1  9  8  5
2  9  1  9

In [77]:
df + df.iloc[0]

A   B   C
0   6  10   6
1  12  13   8
2  12   6  12

In [78]:
df.add(df.iloc[0])

A   B   C
0   6  10   6
1  12  13   8
2  12   6  12

In [79]:
a

array([[3, 5, 3],
       [9, 8, 5],
       [9, 1, 9]])

In [80]:
a - a[0]

array([[ 0,  0,  0],
       [ 6,  3,  2],
       [ 6, -4,  6]])

In [81]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  6  3  2
2  6 -4  6

In [82]:
df.subtract(df['B'], axis=0) #axix=0 열

A  B  C
0 -2  0 -2
1  1  0 -3
2  8  0  8

In [83]:
a ** a[0]

array([[   27,  3125,    27],
       [  729, 32768,   125],
       [  729,     1,   729]], dtype=int32)

In [84]:
df.pow(df.iloc[0])

A      B    C
0   27   3125   27
1  729  32768  125
2  729      1  729

In [85]:
s = pd.Series(range(5), index=['A','D','B','C','E'])

In [86]:
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [87]:
s.sort_index

<bound method Series.sort_index of A    0
D    1
B    2
C    3
E    4
dtype: int64>

In [88]:
s.sort_values  # axis = 1 -- 행 0 : 열

<bound method Series.sort_values of A    0
D    1
B    2
C    3
E    4
dtype: int64>

In [89]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 3, 2])
s.rank()

0    1.0
1    6.0
2    7.5
3    4.5
4    2.0
5    7.5
6    4.5
7    3.0
dtype: float64

In [90]:
s.rank(method = 'first')

0    1.0
1    6.0
2    7.0
3    4.0
4    2.0
5    8.0
6    5.0
7    3.0
dtype: float64

In [93]:
s1 = pd.Series(['a','b'], index=[1,2])
s2 = pd.Series(['c','d'], index=[3,4])
pd.concat([s1,s2])

1    a
2    b
3    c
4    d
dtype: object

In [94]:
def create_df(cols, idx):
    data = {c :[str(c.lower()) + str(i) for i in idx] for c in cols }
    return pd.DataFrame(data, idx)

In [95]:
df1 = create_df('AB',[1,2])
df1

A   B
1  a1  b1
2  a2  b2

In [97]:
df2 = create_df('AB',[3,4])
df2

A   B
3  a3  b3
4  a4  b4

In [98]:
pd.concat([df1,df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [100]:
df3 = create_df('AB',[0,1])
df3

A   B
0  a0  b0
1  a1  b1

In [101]:
df4 = create_df('CD',[0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [110]:
pd.concat([df3,df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [113]:
pd.concat([df1,df3], ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [114]:
pd.concat([df1, df3], keys=['X','Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [118]:
df5 = create_df('ABC',[1,2])
df6 = create_df('BCD',[3,4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [119]:
pd.concat([df5,df6], join='inner') # 둘다 존재하는 데이터에 대해서만 = inner join

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [121]:
df5.append(df6)

C:\Users\ss\AppData\Local\Temp\ipykernel_7068\551904218.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5.append(df6)


A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [127]:
pd.concat([df3,df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [129]:
pd.concat([df1,df3], axis=0)

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [130]:
df1 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '학과': ['경영학과','교육학과','컴퓨터학과','통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [131]:
df2 = pd.DataFrame({'학생': ['홍길동','이순신','임꺽정','김유신'],
                    '입학년도': [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [133]:
df3 = pd.merge(df1,df2) # 학생이 중복되고 기준으로 합쳐짐
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [135]:
df4 = pd.DataFrame({'학과':['경영학과','교육학과','컴퓨터학과','통계학과'],
                  '학과장': ['황희','장영실','안창호','정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [136]:
pd.merge(df3,df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [137]:
df5 = pd.DataFrame({'학과':['경영학과','교육학과','교육학과','컴퓨터학과','컴퓨터학과','통계학과'],
                   '과목':['경영개론','기초수학','물리학','프로그래밍','운영체제','확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [138]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [139]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [140]:
df6 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                    '성적':['A','A+','B','A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [141]:
pd.merge(df1, df6, left_on='학생',right_on='이름') #컬럼명이 다를때

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [142]:
pd.merge(df1, df6, left_on='학생',right_on='이름').drop('이름', axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [143]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [144]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [145]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [146]:
pd.merge(mdf1,mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020