# Pytorch
---

## [1] Tensor 생성
---

In [1]:
import torch

In [2]:
torch.__version__

'1.12.1'

In [3]:
## [기본] tensor(data)
t1 = torch.tensor([1,2,3])

In [4]:
type(t1), t1.shape, t1.dtype, t1.device

(torch.Tensor, torch.Size([3]), torch.int64, device(type='cpu'))

In [5]:
t2 = torch.tensor([1.,2,3])

In [6]:
type(t2), t2.shape, t2.dtype, t2.device

(torch.Tensor, torch.Size([3]), torch.float32, device(type='cpu'))

In [7]:
t3 = torch.tensor([[1.,2,3],[1,2,2]])

In [8]:
type(t3), t3.shape, t3.dtype, t3.device

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [11]:
t4 = torch.ones(size=(10,3)) # 디폴트 : float

In [14]:
t5 = torch.ones_like(t3)
t5

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## Indexing & Slicing

In [15]:
t3

tensor([[1., 2., 3.],
        [1., 2., 2.]])

In [16]:
t3[0]

tensor([1., 2., 3.])

In [17]:
t3[1]

tensor([1., 2., 2.])

In [19]:
t3.ndim, t3.shape

(2, torch.Size([2, 3]))

In [23]:
# [행, 열]
t3[:,0], t3[0,0]

(tensor([1., 1.]), tensor(1.))

In [24]:
tn = t3.numpy()

In [26]:
tn[0] = 100

In [27]:
tn

array([[100., 100., 100.],
       [  1.,   2.,   2.]], dtype=float32)

In [28]:
t3

tensor([[100., 100., 100.],
        [  1.,   2.,   2.]])

In [29]:
torch.cuda.is_available()

False

In [30]:
for _ in range(32):
    print('상언쓰 바보')

상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
상언쓰 바보
