In [1]:
# 모듈 로딩 ----------------------------------------------------
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data, target = load_iris(as_frame=True, return_X_y=True)

In [3]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
train_input, test_input, train_target, test_target = train_test_split(data, target,
                                                                      test_size = 0.2,
                                                                      random_state=42,
                                                                      stratify=target)  

In [5]:
lr = LogisticRegression(multi_class= 'multinomial', max_iter= 100)

In [6]:
lr.fit(train_input, train_target)

LogisticRegression(multi_class='multinomial')

In [7]:
lr.score(train_input,train_target)

0.975

In [8]:
lr.coef_

array([[-5.28109455e-01,  8.25221658e-01, -2.34459091e+00,
        -1.00050556e+00],
       [ 5.29083568e-01, -3.06001763e-01, -1.71908852e-01,
        -8.53566270e-01],
       [-9.74112838e-04, -5.19219895e-01,  2.51649976e+00,
         1.85407183e+00]])

In [9]:
lr.intercept_

array([ 10.12148659,   1.80513046, -11.92661705])

In [10]:
lr.classes_

array([0, 1, 2])

In [11]:
# 결정함수
ret = lr.decision_function([[3,4,1,5]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [12]:
# 시그모이드 함수 / 소프트맥스 후 결과 학인
from scipy.special import softmax, expit

In [13]:
sigValue2 = softmax(ret)
sigValue2

array([[0.99763098, 0.00115384, 0.00121519]])

In [14]:
lr.predict_proba([[3,4,1,5]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.99763098, 0.00115384, 0.00121519]])