# Numpy 패키지 ------------------------------------------------

- pandas에서 데이터를 저장 및 처리에 사용되는 패키지

- 외부 패키지로 반드시 설치 필요

- 고속 데이터 처리, 수치 계산 수행 패키지

- 머신러닝/딥러닝용 패키지 Scikit-lern, Tensorflow, PyTorch, Keras 등등에서도 
- 내부 데이터 저장 및 수치 계산 사용되는 패키지

- [중요] 동일한 데이터 타입의 데이터를 저장하는 배열(Array) 타입!

In [1]:
# 버전 확인
import numpy as np

np.__version__

'1.21.5'

In [3]:
# ndarray 객체 생성하기 ------------------------------------ numpy.array()

arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
type(arr1)

numpy.ndarray

In [8]:
# ndarray 객체 송성 확인하기 --------------------------------------------
# 객체변수명.속성명
# ndim : 차원 (예:1, 2, 3....)
# shape : 형태 ( 예: (갯수), (행, 열), (면, 행, 열))
# dtype : 데이터 타입
# itemsize : 배열 요소의 바이트 크기
# size : 배열 요소 갯수
print(arr1.ndim, arr1.shape, arr1.dtype, arr1.itemsize, arr1.size, sep='\n')

1
(3,)
int32
4
3


In [13]:
# 배열의 요소 즉 아이템, 원소 접근하기 -----------------------------------------------------
# 0-base 인덱스 자동 지정 => 객체변수명[인덱스]

print(f'객체변수명 arr1 => {arr1}')
print(f'객체변수명 arr1 => {arr1[0]}')
print(f'객체변수명 arr1 => {arr1[1]}')

객체변수명 arr1 => [1 2 3]
객체변수명 arr1 => 1
객체변수명 arr1 => 2


In [17]:
# 모든 값을 0으로 채워서 ndarray 객체 생성 함수 => ones()
arr2 = np.array([1,1,1,1])
arr2 = np.ones(4, dtype=np.int64)
arr2

array([1, 1, 1, 1], dtype=int64)

In [18]:
print(arr2.ndim, arr2.shape, arr2.dtype, arr2.itemsize, arr2.size, sep='\n')

1
(4,)
int64
8
4


In [19]:
# 초기화하지 않고 ndarray 객체 생성 => numpy.empty()
arr3 = np.empty((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 2차원 형태의 ndarray 객체 생성

arr_1 = np.ones((4,4))
arr_1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr_1.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
# 1차원 => 다른 차원으로 변경 reshape()

arr_2 = arr_1.reshape((2,8))
arr_2

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
# 차원 / 형태 변환 => reshape(-1,n), reshape(n, -1)
arr8 = np.arange(8)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
arr9 = arr8.reshape(-1,2)
arr9

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])